# 统计代码请直接替换 _partial/footer.ejs 文件里的代码

theme_name: TTStyle
site_url: http://whhqhy.github.io/

# 社交信息
github: "http://github.com/whhqhy"
qq: "http://github.com/whhqhy"


# 是否在新窗口打开链接
open_in_new: true

# favicon
favicon: /images/favicon.png

#你的头像url
avatar: /images/favicon.png

#是否高亮代码。默认开启
highlightCode: true

#代码高亮样式名称
## 内置样式名称5种：idea xcode solarized-dark solarized-light googlecode
highlightStyle: googlecode

#捐赠相关。默认微信打赏
donateEnable: false
